"""increase string lengths

Revision ID: 11ef1a5e4f6c
Revises: ca22c9444fe7
Create Date: 2026-03-13 14:34:08.247168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ef1a5e4f6c'
down_revision: Union[str, Sequence[str], None] = 'ca22c9444fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
